name: main-workflow-test
run-name: ${{ github.actor }}_is_testing_stuff
on:
  push:
    branches:
      - master
      - main

jobs:
  run-java-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: maven test
        
